sudo: required

services:
  - docker

before_install:
  - docker build -t sunkor/sensor-listener ./sensor-listener
  - docker build -t sunkor/sensor-alerts ./sensor-alerts
  - docker build -t sunkor/sensor-listener-proxy ./sensor-listener-proxy
  - docker build -t sunkor/weather-station ./weather-station
  - docker build -t sunkor/grafana ./grafana
  - docker build -t sunkor/home-sensor-nginx ./nginx

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

after_success:
  - docker push sunkor/sensor-listener
  - docker push sunkor/sensor-alerts
  - docker push sunkor/sensor-listener-proxy
  - docker push sunkor/weather-station
  - docker push sunkor/grafana
  - docker push sunkor/home-sensor-nginx
# deploy:
#   provider: elasticbeanstalk
#   region: ap-southeast-2
#   app: home-sensor
#   env: HomeSensor-env-1
#   bucket_name: elasticbeanstalk-ap-southeast-2-068004728410
#   bucket_path: home-sensor
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
