version: "3"
services:
  sensor_listener:
    build:
      dockerfile: sensor-listener.dockerfile
      context: ./sensor-listener
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
  influxdb:
    image: influxdb
    volumes:
      - C:/Users/Sunil/Documents/GitHub/home-sensor/data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    build:
      dockerfile: grafana.dockerfile
      context: ./grafana
    volumes:
      - C:/Users/Sunil/Documents/GitHub/home-sensor/data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
