version: "3"
services:
  sensor-listener:
    build:
      dockerfile: sensor-listener.dockerfile
      context: ./sensor-listener
    depends_on:
      - influxdb
  weather-station:
    build:
      dockerfile: weather-station.dockerfile
      context: ./weather-station
  influxdb:
    image: influxdb
    volumes:
      - C:/Users/Sunil/Documents/GitHub/home-sensor/data/influxdb:/var/lib/influxdb
  grafana:
    build:
      dockerfile: grafana.dockerfile
      context: ./grafana
    volumes:
      - C:/Users/Sunil/Documents/GitHub/home-sensor/data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
